name: test
on:
  pull_request:
  push:
    branches:
      - master
      - release/*
defaults:
  run:
    shell: bash
env:
  official_container_repository: ghcr.io/evalf/nutils
jobs:
  build-python-package:
    name: Build Python package
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: python3 -m pip install setuptools wheel
      - name: Build package
        run: |
          # To make the wheels reproducible, set the timestamp of the (files in
          # the) generated wheels to the date of the commit.
          export SOURCE_DATE_EPOCH=`git show -s --format=%ct`
          python3 setup.py sdist bdist_wheel
      - name: Upload package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-package
          path: dist/
          if-no-files-found: error
  test:
    needs: build-python-package
    name: 'Test os: ${{ matrix.os }}, py: ${{ matrix.python-version }}, matrix: ${{ matrix.matrix-backend }}, nprocs: ${{ matrix.nprocs }}, numpy: ${{ matrix.numpy-version }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # base
          - {os: ubuntu-latest , python-version: 3.8, matrix-backend: numpy, nprocs: 1, numpy-version: latest}
          # os
          - {os: windows-latest, python-version: 3.8, matrix-backend: numpy, nprocs: 1, numpy-version: latest}
          - {os: macos-latest  , python-version: 3.8, matrix-backend: numpy, nprocs: 1, numpy-version: latest}
          # python-version
          - {os: ubuntu-latest , python-version: 3.5, matrix-backend: numpy, nprocs: 1, numpy-version: latest}
          - {os: ubuntu-latest , python-version: 3.6, matrix-backend: numpy, nprocs: 1, numpy-version: latest}
          - {os: ubuntu-latest , python-version: 3.7, matrix-backend: numpy, nprocs: 1, numpy-version: latest}
          # matrix-backend
          - {os: ubuntu-latest , python-version: 3.8, matrix-backend: scipy, nprocs: 1, numpy-version: latest}
          - {os: ubuntu-latest , python-version: 3.8, matrix-backend: mkl  , nprocs: 1, numpy-version: latest}
          - {os: ubuntu-latest , python-version: 3.8, matrix-backend: mkl  , nprocs: 2, numpy-version: latest}
          # nprocs
          - {os: ubuntu-latest , python-version: 3.8, matrix-backend: numpy, nprocs: 2, numpy-version: latest}
          # numpy-version
          - {os: ubuntu-latest , python-version: 3.8, matrix-backend: numpy, nprocs: 1, numpy-version: 1.15  }
      fail-fast: false
    env:
      NUTILS_MATRIX: ${{ matrix.matrix-backend }}
      NUTILS_NPROCS: ${{ matrix.nprocs }}
      OMP_NUM_THREADS: 1
      VECLIB_MAXIMUM_THREADS: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download Python package artifact
        uses: actions/download-artifact@v2
        with:
          name: python-package
          path: dist/
      - name: Install Nutils and dependencies
        env:
          _os: ${{ matrix.os }}
          _matrix: ${{ matrix.matrix-backend }}
          _numpy: ${{ matrix.numpy-version }}
        run: |
          _extras="export_mpl,import_gmsh"
          _deps=coverage
          case "$_os" in
            windows-latest) _deps="$_deps psutil";;
          esac
          case "$_matrix" in
            scipy) _extras=$_extras,matrix_scipy;;
            mkl) _extras=$_extras,matrix_mkl;;
          esac
          case "$_numpy" in
            latest) _extras="$_extras,docs";;
            *) _deps="$_deps numpy==$_numpy";;
          esac
          _wheel=`echo dist/nutils-*-py3-none-any.whl`
          python -um pip install --upgrade pip wheel
          python -um pip install --upgrade $_wheel[$_extras] $_deps
      - name: Test
        run: |
          mv repo/tests repo/examples repo/docs .
          python -um coverage run -m unittest -bq
          python -um coverage xml
      - name: Upload coverage
        uses: codecov/codecov-action@v1
  test-sphinx:
    name: Test building docs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -um pip install setuptools wheel
          python3 -um pip install --upgrade .[docs]
      - name: Build docs
        run: python3 setup.py build_sphinx --nitpicky --warning-is-error --keep-going
  build-and-test-container-image:
    name: Build container image
    needs: build-python-package
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Python package artifact
        uses: actions/download-artifact@v2
        with:
          name: python-package
          path: dist/
      - name: Get base and image tags
        id: tags
        run: python3 -u devtools gha-get-base-and-image-tags
      - name: Pull container base image
        env:
          _base: ${{ env.official_container_repository }}:${{ steps.tags.outputs.base }}
        run: podman pull "docker://$_base"
      - name: Build container image
        id: build
        env:
          _base: ${{ env.official_container_repository }}:${{ steps.tags.outputs.base }}
          _name: ${{ env.official_container_repository }}:${{ steps.tags.outputs.image }}
        run: python3 -u devtools build-container-image --build-from-worktree --name "$_name" --base "$_base"
      - name: Test examples/laplace.py
        env:
          _image: ${{ steps.build.outputs.id }}
        run: podman run --pull=never --rm -v "$PWD/examples:/app:ro" "$_image" -u laplace.py
      - name: Run unit tests
        env:
          _image: ${{ steps.build.outputs.id }}
        run: podman run --pull=never --rm -v "$PWD/tests:/app/tests:ro" -v "$PWD/examples:/app/examples:ro" -v "$PWD/docs:/app/docs:ro" "$_image" -um unittest -bq
      - name: Push image to container registry
        if: ${{ github.event_name == 'push' }}
        env:
          _username: ${{ secrets.DOCKER_USERNAME }}
          _password: ${{ secrets.DOCKER_PASSWORD }}
          _repository: ${{ secrets.DOCKER_REPOSITORY }}
          _image_id: ${{ steps.build.outputs.id }}
          _tag: ${{ steps.tags.outputs.image }}
        run: |
          # Push the image to the official container repository if this
          # workflow is triggered from the official git repository, otherwise
          # use the `DOCKER_REPOSITORY` secret.
          case "$GITHUB_REPOSITORY" in
            evalf/nutils)
              _repository="$official_container_repository"
              ;;
            *)
              if [ -z "$_repository" ]; then
                echo ::error ::"Github secret DOCKER_REPOSITORY is empty"
                exit 1
              fi
              ;;
          esac
          # Login without exposing the password via the command line as recommended by GitHub
          # (https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow).
          printenv _password | podman login --username "$_username" --password-stdin "${_repository%%/*}"
          podman push "$_image_id" "docker://$_repository:$_tag"
